### PR TITLE
dub housekeeping

### PR DESCRIPTION
**Pull request by burner**
removes the auto generated file dub.selections.json

and updates dxml

### CODE REVIEW

**Comment by TransientResponse** [comment]
TIL `dub.selections.json` should be in gitignore

Thank you, kind sir.

**Comment by burner** [comment]
Thanks for merging. Could we also get a new release 0.0.7 perhaps?

**Comment by TransientResponse** [comment]
You've now got your 0.0.7, and even a 0.0.8 to fix some other issues I found.

Also, on an unrelated note, I found your DConf 2019 talk on YouTube. You talked about exactly the reasons why I wrote this library-- Excel being used for things that it shouldn't be at my work, and with sheets that couldn't be easily exported to CSV.

**Comment by burner** [comment]
@TransientResponse thank you

**Pull request merged**
